/**
 * Created by user on 2017/8/23.
 */
//普通消息
const TEXT_TYPE = 'TEXT_MSG';
const VOICE_TYPE = 'VOICE_MSG';
const IMG_TYPE = 'IMG_MSG';

//系统消息

const SYS_CUSTOMER_JOIN = 'SYS_CUSTOMER_JOIN';
const SYS_SERVICE_START = 'SYS_SERVICE_START';
const SYS_EVALUATE_START = 'SYSTEM_EVALUATE_START';
const SYS_CUSTOMER_EVALUATE = 'SYS_CUSTOMER_EVALUATE';
const SYS_SERVICE_END = 'SYS_SERVICE_END';

const SYSTEM_MSG_TYPE = 'SYS_TYPE';
const CHAT_MSG_TYPE = 'CHAT_TYPE';

// 消息内容枚举
const MSG_ELEM = {
    TEXT_ELEM: TEXT_TYPE,
    VOICE_ELEM: VOICE_TYPE,
    IMG_ELEM: IMG_TYPE,
}

//系统消息内容枚举
const SYS_MSG_ELEM = {
    SYS_CUSTOMER_JOIN:SYS_CUSTOMER_JOIN,
    SYS_SERVICE_START:SYS_SERVICE_START,
    SYS_EVALUATE_START:SYS_EVALUATE_START,
    SYS_CUSTOMER_EVALUATE:SYS_CUSTOMER_EVALUATE,
    SYS_SERVICE_END:SYS_SERVICE_END
}

// 消息类型枚举
const MSG = {
    SYSTEM: SYSTEM_MSG_TYPE,
    CHAT_MSG: CHAT_MSG_TYPE,
}
module.exports = {
    MSG_ELEM:MSG_ELEM,
    MSG:MSG,
    SYS_MSG_ELEM:SYS_MSG_ELEM
}